# Configuration file for classifier-based router evaluation (think/no_think)

# Model configuration
model:
  id: "AmirMohseni/qwen3-0.6b-router-classifier-lr1e-5-ep2"
  
# Label mapping
labels:
  0: "no_think"
  1: "think"

# Dataset configuration
dataset:
  name: "AmirMohseni/WildChat-filtered-Qwen3-8B-Splits"
  split: "test"
  prompt_column: "prompt"

# Processing configuration
processing:
  batch_size: 1
  max_length: 4096

# Output configuration
output:
  results_dir: "evaluations/results"
  filename: "router_predictions.jsonl"

# Device preference (will auto-detect the best available)
# Options: "auto", "cuda", "mps", "cpu"
device:
  preference: "auto"
